name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create release zip
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir -p dist
          zip -r "dist/menuscript-${VERSION}.zip" . -x .git\* venv\* dist\*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: menuscript-${{ github.ref_name }}-zip
          path: dist/menuscript-${{ github.ref_name }}.zip
